#ifndef CALLBACKMESSAGETYPES_H
#define CALLBACKMESSAGETYPES_H

#define CB_MSG_STATUS 1
#define CB_MSG_SESSION 2
#define CB_MSG_COMPLETE 3
#define CB_MSG_ERROR 4

#endif /* CALLBACKMESSAGETYPES_H */
